import Mathlib.Data.Rat.Basic
import Mathlib.LinearAlgebra.Matrix.Basic

/-! # Automatically Sanitized & Generated by SO-HMNS Engine - Zero Numerical Leakage -/ 

def so_hmns_computed_matrix : Matrix (Fin 3) (Fin 3) ℚ :=
  !![
  3/10, 0/1, 0/1;
  0/1, 2/3, 0/1;
  0/1, 0/1, 9/20
  ]

/-- Verifies that the translated matrix preserves absolute determinant unity tightly. --/
theorem verify_solver_determinant : |Matrix.det so_hmns_computed_matrix| = 9/100 := by
  rfl
