import Mathlib.Data.Rat.Basic
import Mathlib.LinearAlgebra.Matrix.Basic

/-! # Automatically Sanitized & Generated by SO-HMNS Engine - Zero Numerical Leakage -/ 

def so_hmns_computed_matrix : Matrix (Fin 2) (Fin 2) ℚ :=
  !![
  3/5, 4/5;
  (-4/5), 3/5
  ]

/-- Verifies that the translated matrix preserves absolute determinant unity tightly. --/
theorem verify_solver_determinant : |Matrix.det so_hmns_computed_matrix| = 1/1 := by
  rfl
